sudo: false

language: ruby

cache:
- bundler

matrix:
    fast_finish: true
    include:
        rvm:
        - 1.8.7
        - 1.9.3
        - 2.0.0
        - 2.1.7
        - 2.2.3
        - jruby
        os:
        - linux
        - osx

script:
- rspec

